; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = -I src
monitor_raw = true
monitor_echo = true
platform = espressif32
board = ttgo-lora32-v21
framework = arduino
monitor_speed = 115200
lib_deps = 
	sandeepmistry/LoRa@^0.8.0
	adafruit/Adafruit SSD1306@^2.5.13
	adafruit/Adafruit GFX Library@^1.11.11
	arduinogetstarted/ezButton@^1.0.6
	jgromes/RadioLib@^7.1.2
	bblanchon/ArduinoJson@^7.3.1

[env:lora1]
upload_port = COM4
monitor_port = COM4

[env:lora2]
upload_port = COM3
monitor_port = COM3
