; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = ttgo-lora32-v21
test_build_src = true
framework = arduino
monitor_speed = 115200
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    jgromes/RadioLib@^7.1.2
    h2zero/NimBLE-Arduino@^2.5.0
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.2
    
; [env:device1]
; upload_port = COM7
; monitor_port = COM7
; build_flags = 
;     -D LORA_ADDRESS=0x01

; [env:device2]
; upload_port = COM6
; monitor_port = COM6
; build_flags = 
;     -D LORA_ADDRESS=0x02

[env:device3]
extends = env
board = ttgo-lora32-v21
upload_port = /dev/ttyACM0
build_flags = 
    -D LORA_ADDRESS=0x03
    -D NODE_TYPE=CAPTURE_POINT
    -D SX_CHIP_TYPE=RA_02_SX1278
    -D SCREEN_TYPE=LCD_SMOLL_SCREEN
    -D BUZZER_GENERATOR=BUZZER_OFF

[env:device4]
extends = env
board = ttgo-lora32-v21
upload_port = /dev/ttyACM1
build_flags = 
    -D LORA_ADDRESS=0x04
    -D NODE_TYPE=CAPTURE_POINT
    -D SX_CHIP_TYPE=RA_02_SX1278
    -D SCREEN_TYPE=LCD_SMOLL_SCREEN
    -D BUZZER_GENERATOR=BUZZER_OFF

[env:device5]
extends = env
board = ttgo-lora32-v21
upload_port = /dev/ttyUSB1
build_flags = 
    -D LORA_ADDRESS=0x05
    -D NODE_TYPE=INFORMATION
    -D SX_CHIP_TYPE=RA_02_SX1278
    -D SCREEN_TYPE=LCD_CHONKY_SCREEN
    -D BUZZER_GENERATOR=BUZZER_OFF

[env:device6]
extends = env
board = ttgo-lora32-v21
upload_port = /dev/ttyUSB0
build_flags = 
   -D LORA_ADDRESS=0x06
   -D NODE_TYPE=INFORMATION
   -D SX_CHIP_TYPE=RA_02_SX1278
   -D SCREEN_TYPE=LCD_CHONKY_SCREEN
   -D BUZZER_GENERATOR=BUZZER_OFF

[env:device7]
extends = env
board = ttgo-lora32-v21
upload_port = /dev/ttyUSB0
build_flags = 
   -D LORA_ADDRESS=0x07
   -D NODE_TYPE=CAPTURE_POINT
   -D SX_CHIP_TYPE=RA_02_SX1278
   -D SCREEN_TYPE=LCD_SMOLL_SCREEN
   -D BUZZER_GENERATOR=BUZZER_OFF

[env:headless]
extends = env
board = heltec_wifi_lora_32_V3
upload_port = /dev/ttyUSB0
build_flags = 
   -D LORA_ADDRESS=0x0A
   -D NODE_TYPE=HEADLESS
   -D SX_CHIP_TYPE=HELTECSX1262
   -D SCREEN_TYPE=OLED_128x36_SCREEN
   -D BUZZER_GENERATOR=BUZZER_OFF

[env:deviceBLEToLoRa]
extends = env
board = heltec_wifi_lora_32_V3
upload_port = /dev/ttyUSB0
build_flags = 
    -D LORA_ADDRESS=0x0B
    -D NODE_TYPE=BLEToLoRa 
    -D SX_CHIP_TYPE=HELTECSX1262
    -D SCREEN_TYPE=OLED_128x36_SCREEN
    -D BUZZER_GENERATOR=BUZZER_OFF

; [env:deviceForwarder]
; extends = env
; board = heltec_wifi_lora_32_V3
; upload_port = /dev/ttyUSB0
; build_flags = 
;     -D LORA_ADDRESS=0x0C
;     -D NODE_TYPE=FORWARDER 
;     -D SX_CHIP_TYPE=HELTECSX1262
;     -D SCREEN_TYPE=OLED_128x36_SCREEN
;     -D BUZZER_GENERATOR=BUZZER_OFF

; [env:native_test]
; platform = native
; framework = unity
; test_ignore = test_device
; test_build_src = true
; build_flags = 
;     -std=c++11
;     -DUNIT_TEST  ; Define this so you can #ifdef in code
;     -D LORA_ADDRESS=0x01    -std=c++11
;     -DUNIT_TEST  ; Define this so you can #ifdef in code
;     -D LORA_ADDRESS=0x01