; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = espressif32
board = ttgo-lora32-v21
test_build_src = true
framework = arduino
monitor_speed = 115200
lib_deps = 
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
    jgromes/RadioLib@^7.1.2
    h2zero/NimBLE-Arduino@^2.3.1

; [env:device1]
; upload_port = COM7
; monitor_port = COM7
; build_flags = 
;     -D LORA_ADDRESS=0x01

; [env:device2]
; upload_port = COM6
; monitor_port = COM6
; build_flags = 
;     -D LORA_ADDRESS=0x02

[env:device3]
extends = env
upload_port = /dev/ttyACM1
build_flags = 
    -D LORA_ADDRESS=0x03

[env:device4]
extends = env
upload_port = /dev/ttyACM0
build_flags = 
    -D LORA_ADDRESS=0x04
; big screen = 4x20
; [env:device5]
; extends = env
; ; upload_port = /dev/ttyACM2
; build_flags = 
;     -D LORA_ADDRESS=0x14
;     -BIG_SCREEN

; [env:device6]
; extends = env
; ; upload_port = /dev/ttyACM3
; build_flags = 
;     -D LORA_ADDRESS=0x15
;     -BIG_SCREEN

; [env:native_test]
; platform = native
; framework = unity
; test_ignore = test_device
; test_build_src = true
; build_flags = 
;     -std=c++11
;     -DUNIT_TEST  ; Define this so you can #ifdef in code
;     -D LORA_ADDRESS=0x01