#ifndef EVENT_CODES_H
#define EVENT_CODES_H

// Auto-generated event codes - DO NOT EDIT MANUALLY
// Generated from generate_events.py

#define EVENT_GAME_START 1
#define EVENT_GAME_END 2
#define EVENT_POINT_YELLOW_BUTTON 101
#define EVENT_POINT_BLUE_BUTTON 102
#define EVENT_POINT_CAPTURED_BY_BLUE 103
#define EVENT_POINT_CAPTURED_BY_YELLOW 104
#define EVENT_POINT_NEUTRALIZED 105
#define EVENT_SYSTEM_SEND_CONFIG 201
#define EVENT_SYSTEM_RECEIVE_CONFIG 202
#define EVENT_SYSTEM_RECEIVED_NODE_INFO 203
#define EVENT_SYSTEM_RESTARTING_NODE 204
#define EVENT_SYSTEM_ID_MAIN_NODE 205
#define EVENT_SYSTEM_SEND_NODE_INFO 206
#define EVENT_SYSTEM_STARTUP 207

#endif // EVENT_CODES_H
